name: Build luci-app-npc for OpenWrt 24.10 Snapshot (x86_64)

on:
  workflow_dispatch: # 允许手动触发
  push:
    paths:
      - 'luci-app-npc/**'
      - 'nps/**'
    branches: [ "main", "master" ]
  pull_request:
    paths:
      - 'luci-app-npc/**'
      - 'nps/**'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
      options: --privileged

    steps:
      - name: Install dependencies (including Git and zstd)
        run: |
          apt-get update
          # 安装 OpenWrt 构建所需的所有必要依赖
          apt-get install -y \
            build-essential \
            clang \
            gawk \
            gcc-multilib \
            g++-multilib \
            gettext \
            libncurses5-dev \
            libncursesw5-dev \
            libssl-dev \
            python3-distutils \
            rsync \
            unzip \
            zlib1g-dev \
            file \
            wget \
            git \
            subversion \
            quilt \
            libelf-dev \
            zstd \
            ccache \
            python3-setuptools \
            python3-dev \
            swig \
            time \
            ecj \
            fastjar \
            java-propose-classpath \
            libxml2-utils \
            xsltproc \
            lib32z1-dev \
            libc6-dev-i386

      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Download OpenWrt 24.10 SDK (.tar.zst format)
        run: |
          SDK_URL="https://downloads.openwrt.org/snapshots/targets/x86/64/openwrt-sdk-x86-64_gcc-14.3.0_musl.Linux-x86_64.tar.zst"
          echo "Downloading SDK from: $SDK_URL"
          wget -q --tries=3 --timeout=30 "$SDK_URL" -O openwrt-sdk.tar.zst
          
          if [ ! -s "openwrt-sdk.tar.zst" ]; then
            echo "Error: Failed to download SDK or file is empty"
            exit 1
          fi

      - name: Extract SDK
        run: |
          zstd -d -c openwrt-sdk.tar.zst | tar -x
          rm openwrt-sdk.tar.zst
          
          EXTRACTED_DIR=$(find . -maxdepth 1 -type d -name "openwrt-sdk-*" | head -1)
          if [ -z "$EXTRACTED_DIR" ]; then
            echo "Error: Could not find extracted SDK directory"
            exit 1
          fi
          mv "$EXTRACTED_DIR" openwrt-sdk
          echo "SDK extracted to: $(pwd)/openwrt-sdk"

      - name: Prepare SDK and link packages
        run: |
          cd openwrt-sdk
          echo "Linking your packages to SDK..."
          ln -sf "$GITHUB_WORKSPACE/luci-app-npc" package/
          ln -sf "$GITHUB_WORKSPACE/nps" package/
          
          echo "Contents of package directory after linking:"
          ls -la package/ | grep -E "(nps|luci-app-npc)"
          
          # 强制满足依赖检查
          FORCE=1 ./scripts/feeds update -a
          FORCE=1 ./scripts/feeds install libc

      - name: Configure build (with FORCE=1)
        run: |
          cd openwrt-sdk
          echo "CONFIG_TARGET_x86_64=y" > .config
          echo "CONFIG_TARGET_x86_64_Default=y" >> .config
          echo "CONFIG_PACKAGE_luci-app-npc=y" >> .config
          echo "CONFIG_PACKAGE_npc=y" >> .config
          echo "CONFIG_PACKAGE_luci-i18n-npc-zh-cn=y" >> .config
          
          # 使用 FORCE=1 跳过依赖检查
          FORCE=1 make defconfig
          
          echo "Final configuration:"
          grep -E "(CONFIG_TARGET|CONFIG_PACKAGE)" .config

      - name: Build packages (with FORCE=1)
        run: |
          cd openwrt-sdk
          make package/nps/clean 2>/dev/null || true
          
          echo "Building npc package (via nps Makefile)..."
          # 注意：这里的目标是 nps，因为 PKG_NAME:=nps
          FORCE=1 make package/nps/compile V=sc -j$(nproc)
          
          echo "Building luci-app-npc package..."
          FORCE=1 make package/luci-app-npc/compile V=sc -j$(nproc)

      - name: Check build results
        run: |
          cd openwrt-sdk
          echo "Searching for built packages..."
          find . -name "*.ipk" | grep -E "(npc|luci-app-npc)" | while read file; do
            echo "Found: $file"
            basename "$file"
          done
          
          NPC_IPK=$(find bin -name "npc_*.ipk" | head -1)
          if [ -f "$NPC_IPK" ]; then
            echo "=== NPC PACKAGE VERSION INFO ==="
            echo "Filename: $(basename $NPC_IPK)"
            tar -xf "$NPC_IPK" control.tar.gz
            tar -xzf control.tar.gz ./control 2>/dev/null || true
            if [ -f "control" ]; then
              echo "Control file version info:"
              grep -E "Version|Package" control
              rm control control.tar.gz
            fi
          else
            echo "ERROR: Could not find npc IPK file!"
            exit 1
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-24.10-npc-packages
          path: |
            openwrt-sdk/bin/packages/*/base/npc_*.ipk
            openwrt-sdk/bin/packages/*/base/luci-app-npc_*.ipk
            openwrt-sdk/bin/packages/*/base/luci-i18n-npc-zh-cn_*.ipk
          if-no-files-found: error
          
      - name: Show package versions summary
        run: |
          cd openwrt-sdk
          echo "=== BUILD SUMMARY ==="
          for ipk in $(find bin -name "*.ipk" | grep -E "(npc|luci-app-npc)"); do
            echo "Package: $(basename $ipk)"
          done
          echo "====================="
