name: Build OpenWrt AMD x86-64 Packages

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
            gettext git libncurses-dev libssl-dev rsync unzip zlib1g-dev file wget python3 python3-venv python3-pip

      - name: Download OpenWrt SDK
        run: |
          OWRT_VERSION=23.05.3
          SDK_URL="https://downloads.openwrt.org/releases/${OWRT_VERSION}/targets/x86/64/openwrt-sdk-${OWRT_VERSION}-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz"
          wget $SDK_URL
          tar -xf openwrt-sdk-*.tar.xz
          SDK_DIR=$(find . -maxdepth 1 -type d -name "openwrt-sdk-*")
          mv "$SDK_DIR" openwrt-sdk

      - name: Copy packages to SDK package directory
        run: |
          find . -maxdepth 1 -mindepth 1 -type d ! -name 'openwrt-sdk' ! -name '.git' -exec cp -r {} openwrt-sdk/package/ \;

      - name: Build all packages
        working-directory: openwrt-sdk
        run: |
          ./scripts/feeds update -a || true
          ./scripts/feeds install -a || true
          make defconfig
          for pkg in ../package/*; do
            [ -d "$pkg" ] && make package/$(basename $pkg)/compile V=s || true
          done

      - name: Collect compiled ipks and compress
        run: |
          mkdir -p output
          find openwrt-sdk/bin/packages/ -name "*.ipk" -exec cp {} output/ \;
          cd output
          zip -r ../all-ipks.zip ./
          cd ..

      - name: Upload all compiled ipks as artifact
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-amd64-ipks
          path: all-ipks.zip
