name: Build All OpenWrt Packages

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
          gettext git libncurses-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget

    - name: Download OpenWrt SDK
      run: |
        export OWRT_VERSION=23.05.3
        export OWRT_TARGET=x86_64
        wget https://downloads.openwrt.org/releases/${OWRT_VERSION}/targets/x86/64/openwrt-sdk-${OWRT_VERSION}-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz
        tar -xf openwrt-sdk-*.tar.xz
        mv openwrt-sdk-* openwrt-sdk

    - name: Copy packages to SDK
      run: |
        cp -r ./* openwrt-sdk/package/

    - name: Build all packages
      working-directory: openwrt-sdk
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        make defconfig
        for pkg in ../package/*; do
          if [ -d "$pkg" ]; then
            make package/$(basename $pkg)/compile V=s || true
          fi
        done

    - name: Upload packages
      uses: actions/upload-artifact@v4
      with:
        name: openwrt-packages
        path: openwrt-sdk/bin/packages/
