      - name: Download nps source manually (Fix for 404 error)
        run: |
          cd openwrt-sdk
          mkdir -p dl
          echo "Manual downloading nps source to avoid 404..."
          # 使用正确的URL手动下载源码包
          wget -O dl/nps-0.26.26.tar.gz https://github.com/yisier/nps/archive/refs/tags/v0.26.26.tar.gz
          # 计算实际哈希值并输出
          echo "Actual SHA256 hash of downloaded file:"
          sha256sum dl/nps-0.26.26.tar.gz | cut -d ' ' -f 1
          # 然后尝试验证（如果失败，我们会看到期望的哈希值，并且工作流会失败，但我们已经输出了实际哈希值）
          echo "1c73f9cdf54c1ae12dd1c58e43d7e6402a19ae11fe92dc6b77f0ffb6b101a066  dl/nps-0.26.26.tar.gz" | sha256sum -c -
