      - name: Download nps source and calculate hash
        run: |
          cd openwrt-sdk
          mkdir -p dl
          echo "Downloading nps source..."
          wget -O dl/nps-0.26.26.tar.gz https://github.com/yisier/nps/archive/refs/tags/v0.26.26.tar.gz
          
          # 计算并输出实际的 SHA256 哈希值
          echo "Actual SHA256 hash:"
          sha256sum dl/nps-0.26.26.tar.gz | cut -d' ' -f1
          
          # 输出文件大小
          echo "File size:"
          du -h dl/nps-0.26.26.tar.gz
